name: CI workflow
run-name: CI for ${{ github.repository }}

on: [push]

jobs:
  job_Unit-Tests:
    runs-on: ubuntu-latest
    environment: TEST
    container: node:21-alpine3.19
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install mongoose
        run: npm install mongoose

      - name: Test Mongo Service with client
        run: node client.js
        env:
            MONGO_HOST: ${{ vars.MONGO_HOST }}
            MONGO_PORT: ${{ vars.MONGO_PORT }}

      - name: Install all dependencies
        run: npm ci

      - name: Roll-up the Unit Tests
        run: npm run ci-test
        env:
            ENV: ci
            MONGO_HOST: ${{ vars.MONGO_HOST }}
            MONGO_PORT: ${{ vars.MONGO_PORT }}

