name: CI workflow
run-name: CI for ${{ github.repository }}

on: [push]

jobs:
  mongo-service-container-test-job:
    runs-on: ubuntu-latest
    container: node:21-alpine3.19
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand("ping").ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Print a Welcome message
        run: echo "Welcome in GitHub Actions!"